### ISSUE TITLE
Check order of elements for each collection.. not just its contain

### ISSUE THREAD

**Issue by gd-atrygub** [Equ1v/learnJava#3]
https://github.com/Equ1v/learnJava/blob/50642336aba5c484ac8713e510c0472ec5145ec1/src/test/java/com/equiv/java/AppTest.java#L137

**Comment by Equ1v** [comment]
but method contains() checks that collection contained values in specific order

**Comment by Equ1v** [comment]
Added checking order in ArrayList and LinkedList by combination of methods size() & contains(). Please take a look
